# Generated by Django 5.2.1 on 2025-05-19 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tarea',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='uuid',
            field=models.TextField(default='Sin uuid', max_length=200),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.TextField(default='Sin título', max_length=100),
        ),
    ]
